### ISSUE TITLE
Companies information not displayed on mobile page. 

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#117]
When selecting a company all information (name, website, address etc) are no longer available. 

![untitled](https://user-images.githubusercontent.com/32377726/32219945-2e586884-be30-11e7-9897-9819e576e9e7.png)

**Comment by jamesmillerburgess** [comment]
Probably related to #119

**Comment by jamesmillerburgess** [comment]
Issue seems to be resolved, though I'm not sure why.
