### ISSUE TITLE
All fields overlapping Contacts - under Iphone 6+

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#119]
When opening an opportunity all fields (company information - contacts and notes etc) are not longer aligned properly. 

![capture](https://user-images.githubusercontent.com/32377726/32220551-6d7909ea-be32-11e7-8908-6ae0bea4a12f.JPG)

**Comment by jamesmillerburgess** [comment]
Having trouble reproducing this one:
* Not happening on Samsung phones
* Not happening on iPhone SE
* Not happening on iPhone 6

* Happens on Alex's iPhone 6+

**Comment by jamesmillerburgess** [comment]
Issue seems to be resolved, though I'm not sure why.
