### ISSUE TITLE
Screen Resolution Iphone 6+ versus SamsungA5  2017

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#129]
Just made a quick comparison Iphone versus Samsung. Noticed that the display of the fields are different when looking at a contact  

Reasons ? 
- Screen resolution ? 
- Length of the fields ? 

![capture](https://user-images.githubusercontent.com/32377726/32265110-ed30b5f2-bee1-11e7-8e9e-4c2d7688a641.JPG)

**Comment by jamesmillerburgess** [comment]
I'm thinking I should hide those fields in the mobile layout since they are repeated immediately below.

**Comment by alexandreabou** [comment]
Yes that could be a valid option. Would agree to do so :+1:
