### ISSUE TITLE
Team information not showing on Dashboard

### ISSUE THREAD

**Issue by michelinegreber** [jamesmillerburgess/customer-management#130]
I just logged in with my iPad mini and it is not showing my team info on the dashboard.

**Comment by michelinegreber** [comment]
Actually that is happening on all my devices

**Comment by michelinegreber** [comment]
on my macBookPro using Safari:

<img width="1280" alt="bildschirmfoto 2017-11-01 um 09 01 58" src="https://user-images.githubusercontent.com/31616711/32265461-6c683308-bee3-11e7-8c15-bcea0656479e.png">

**Comment by michelinegreber** [comment]
it seems like all my team activities have been deleted - when I add new things they show again in the dashboard

however only one thing and the one before is deleted....

**Comment by alexandreabou** [comment]
I will let James comment on this but the Dashboard only show activity for the current month if nothing has been done during November no information will be displayed. 

Same for opportunity forecast :)

**Comment by michelinegreber** [comment]
oh yes you are right - thanks alex!!
