### ISSUE TITLE
Opportunities Screen - Summary not showing on every device

### ISSUE THREAD

**Issue by michelinegreber** [jamesmillerburgess/customer-management#144]
I noticed that on Google Chrome I can reduce the window size and the summary is always showing in the same screen without need for scrolling.
In the iPad mini and the iPhone I need to scroll down to see the summary of each column.

On Windows 10 - Google Chrome
![image](https://user-images.githubusercontent.com/31616711/32325890-14099a8c-bfd1-11e7-908d-da316434c854.png)

On iPad mini - Safari
![img_0286](https://user-images.githubusercontent.com/31616711/32325992-8d5becbe-bfd1-11e7-9275-47a2f3b4e621.PNG)

On iPhone 5SE - Safari
![img_1756](https://user-images.githubusercontent.com/31616711/32326010-9deb534e-bfd1-11e7-8c15-c762c86160a5.PNG)

**Comment by jamesmillerburgess** [comment]
This is due to the auto-collapsing address bar on mobile browsers. I've looked around for a solution but haven't found anything elegant yet.
