### ISSUE TITLE
Unable to locate where to edit and enter company details 

### ISSUE THREAD

**Issue by alexandreabou** [jamesmillerburgess/customer-management#23]
![capture](https://user-images.githubusercontent.com/32377726/30996764-c7317414-a4f5-11e7-9bd0-f2884131e16a.JPG)

When entering company details it is not obvious to locate where we can enter the information. Unless click with the mouse cursor we can view the space to enter information.

Should be more obvious in terms of usability

**Comment by jamesmillerburgess** [comment]
<img width="373" alt="screen shot 2017-09-29 at 6 39 11 am 2" src="https://user-images.githubusercontent.com/15968012/31001055-ffe4246a-a4e0-11e7-96b8-9830ba0d2ce0.png">

Does this look better?
