### ISSUE TITLE
Add opportunities - Company content not showing

### ISSUE THREAD

**Issue by michelinegreber** [jamesmillerburgess/customer-management#50]
When adding a new opportunity and searching for a company and clicking on it - it is not showing the selected company in the field. If you close the field the opportunity is showing for the selected company.
Issue is just in the "add opportunites" screen.

**Comment by jamesmillerburgess** [comment]
This happens when in the same session, a user creates a company and then subsequently selects it in a company field.

The issue goes away after a refresh, so it might be connected to subscriptions.
